### ISSUE TITLE
ngtags input  autocomplete not working correctly

### ISSUE THREAD

**Issue by tippuafsar** [mbenford/ngTagsInput#564] opened 2015-11-13 00:01 UTC
Hi 

I have used ng tags input, i am facing an issue with its auto complete, i have binded it from server and it is fetching the data from database using service, so when the user types first three characters it fetches the data from database and displays it in autocomplete, but some time it doesn't  work correctly as if i type first three characters as "abc" and it will return the records "abcd, abcde" and if i add one more character which would be i and the new characters of string is "abci" it still returns "abcd"  only and it seems the call doesn't go to the server as well in this case  and some times it return the correct record "abci", i am unable to figure out the issue may, please help me  with this one, thanks in advance.

Regards

**Comment by tippuafsar** [comment] 2015-11-13 00:15
Hi 

I have found some thing, basically it s not the issue its not sending the request to database it does but in case i type abc it shows records as "abcd, abcde,abci" and if i type i at the end it shows "abcd" only but if i hit enter button it insert the tag as "abci" but it is not displayed in the list and some time its being displayed and you have to select it or in case you hit the back space and insert i at the end again it will show "abci" in the autocomplete, i want it to show "abci"  in autocomplete in first instance too so user should be able to select it from the auto complete list.  Please let me know about it.

Regards,

**Comment by mmeloni** [comment] 2016-03-29 12:38
+1

**Comment by mmeloni** [comment] 2016-03-29 12:39
Possible duplicate of #599 ?

**Comment by mbenford** [comment] 2017-04-17 02:40
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Closed by mbenford** 2017-04-17 02:40 UTC
Labels: spring-cleaned
