### ISSUE TITLE
select-first-match appear doesn't work properly

### ISSUE THREAD

**Issue by cguilhermef** [mbenford/ngTagsInput#625] opened 2016-02-11 18:38 UTC
I think that this option enable to add the first item from autocomplete list that is highlighted, but it doesn't work like.

If I have this list: 

apple, 
banana, 
cherry

And I type in input "ana":

apple
b**ana**na
cherry

And a hit 'Enter', the 'banana' should be selected. Or not?

**Comment by duncangrist** [comment] 2016-03-03 15:22
Are you running Angular 1.5? I've managed to reproduce the exact same bug after I upgraded to 1.5.

For me, it seems to be caused by a change in the registration order of the `input-keydown` event on both the editor and the autocomplete dropdown; the order has been reversed in Angular 1.5. This causes the editor to receive the ENTER key press *before* the autocomplete dropdown, closing the dropdown and simply creating a tag based on the partial string you've typed (just as it would if the autocomplete dropdown wasn't being used).

**Comment by mbenford** [comment] 2017-04-17 02:41
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Closed by mbenford** 2017-04-17 02:42 UTC
Labels: spring-cleaned
