### ISSUE TITLE
findInObjectArray is not returning the expected result

### ISSUE THREAD

**Issue by silvanaacc** [mbenford/ngTagsInput#630] opened 2016-02-21 18:33 UTC
Hi guys,
first, thank you very much for this plugin.
As I try to add more than one tag, I get the second being invalid; after a research, I found out that this the line 
`!tiUtil.findInObjectArray(self.items, tag, options.keyProperty || options.displayProperty)`
in the following code return false and this is why the tag is not added

`return tagText &&
                   tagText.length >= options.minLength &&
                   tagText.length <= options.maxLength &&
                   options.allowedTagsPattern.test(tagText) &&
                   !tiUtil.findInObjectArray(self.items, tag, options.keyProperty || options.displayProperty) &&
                   onTagAdding({ $tag: tag });`

**Comment by silvanaacc** [comment] 2016-02-21 18:42
I think I found the source of this issue. It is because i set key different from displayed property. So, when a new tag is created, only the displayed property is set. So the function, consider the new word as a duplicate, duplicate in the key that is actually undefined.
Am I correct?

**Comment by guilbep** [comment] 2016-03-21 13:26
@silvanaacc Isn't that a duplicate of https://github.com/mbenford/ngTagsInput/issues/470 ?

**Comment by mbenford** [comment] 2017-04-17 02:42
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Closed by mbenford** 2017-04-17 02:42 UTC
Labels: spring-cleaned
