### ISSUE TITLE
Add keyup event for model changed ( for non ascii )

### ISSUE THREAD

**Issue by qpitlove** [mbenford/ngTagsInput#303] opened 2014-11-29 14:20 UTC
it's enough use only ng-change directive  if alpha or number characters is input,
but Non-English speaking country character need to check keyup event for last character input changing

reference : https://code.angularjs.org/1.2.27/docs/api/ng/type/ngModel.NgModelController
check this out :  Listen for change events element.on('blur keyup change', function() { ...

so I want to merge it below pr
https://github.com/mbenford/ngTagsInput/pull/302

**Comment by mbenford** [comment] 2015-01-17 22:59
I was able to reproduce your problem, but I'm not sure how to correctly fix it. Angular itself won't bind the input to the model at every keystroke - that's due to the fact that the browser does not trigger the `input` event at every keystroke as well.

I'll try to find out how this problem is addressed by the Angular community.

**Comment by qpitlove** [comment] 2015-01-29 08:29
sorry to late reply!

I was found that it's angular problem.
keydown event binding of angular consider compositionstart and compositionend event.
in composition mode, users are still inputing intermediate text buffer, hold ther listener until composition is done. it's useful japan or china key input system ( keydown event is doing and composite word, and show list that want to convert katakana character or Chinese character)
but korean input must recognize when composition doing

so I made some directive. and use my service
```
angular.module('hiveTaskTrackerApp')
    .directive('ignoreCompositionEvent', function () {
        return {
            restrict: 'A',
            link: function postLink(scope, element) {
                //element.val('this is the ignoreCompositionEvent directive');
                element.off('compositionstart').off('compositionend');
                //element.text('this is the updateOnComposition directive');
            }
        };
    });
```

Thank's for your attention!! ^^

**Comment by grapemix** [comment] 2015-03-09 01:05
Chinese is not working too

**Comment by mbenford** [comment] 2017-04-17 02:33
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Closed by mbenford** 2017-04-17 02:33 UTC
Labels: spring-cleaned, status: replied
